"""
Page2PDF — PDF Merger
Merges multiple PDFs into a single document, adding cover pages, separators, and TOC.
"""

import os
import logging
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional, Tuple

import fitz  # PyMuPDF

from app.utils.file_utils import get_output_dir, generate_unique_filename

logger = logging.getLogger(__name__)

def create_cover_page(title: str, num_sources: int, total_pages: int, output_path: Path):
    """Creates a simple cover page PDF."""
    doc = fitz.open()
    page = doc.new_page()
    
    generation_date = datetime.now().strftime("%d %B %Y")
    
    # Simple layout
    rect = page.rect
    
    # Title
    p = fitz.Point(50, 150)
    page.insert_text(p, title, fontsize=24, fontname="helv", color=(0, 0, 0))
    
    # Metadata
    p = fitz.Point(50, 200)
    page.insert_text(p, "Generated by Page2PDF", fontsize=14, fontname="helv", color=(0.4, 0.4, 0.4))
    
    p = fitz.Point(50, 230)
    page.insert_text(p, f"Number of sources: {num_sources}", fontsize=12, fontname="helv", color=(0, 0, 0))
    
    p = fitz.Point(50, 250)
    page.insert_text(p, f"Total pages: {total_pages}", fontsize=12, fontname="helv", color=(0, 0, 0))
    
    p = fitz.Point(50, 270)
    page.insert_text(p, f"Generated date: {generation_date}", fontsize=12, fontname="helv", color=(0, 0, 0))
    
    doc.save(output_path)
    doc.close()

def create_separator_page(source_num: int, title: str, url: str, output_path: Path):
    """Creates a separator page for a source."""
    doc = fitz.open()
    page = doc.new_page()
    
    # Separator Line
    page.draw_line(fitz.Point(50, 100), fitz.Point(550, 100), color=(0.5, 0.5, 0.5), width=2)
    
    # Source Number
    p = fitz.Point(50, 130)
    page.insert_text(p, f"SOURCE {source_num}", fontsize=14, fontname="helv", color=(0.3, 0.3, 0.3))
    
    # Title
    p = fitz.Point(50, 170)
    page.insert_text(p, title or "Untitled", fontsize=20, fontname="helv", color=(0, 0, 0))
    
    # URL
    p = fitz.Point(50, 210)
    page.insert_text(p, "Source:", fontsize=12, fontname="helv", color=(0.3, 0.3, 0.3))
    p = fitz.Point(50, 230)
    page.insert_text(p, url, fontsize=10, fontname="helv", color=(0.1, 0.4, 0.8))
    
    # Separator Line
    page.draw_line(fitz.Point(50, 270), fitz.Point(550, 270), color=(0.5, 0.5, 0.5), width=2)
    
    doc.save(output_path)
    doc.close()


def create_contents_pdf(entries: List[List], target_offset: int) -> fitz.Document:
    """Create a polished, clickable Contents section for the merged PDF."""
    contents_doc = fitz.open()
    entries_per_page = 28
    chunks = [entries[index:index + entries_per_page] for index in range(0, len(entries), entries_per_page)]
    chunks = chunks or [[]]

    for chunk_index, chunk in enumerate(chunks):
        page = contents_doc.new_page(width=595, height=842)
        page.insert_text(
            fitz.Point(54, 72),
            "Contents" if chunk_index == 0 else "Contents (continued)",
            fontsize=25,
            fontname="helv",
            color=(0.08, 0.11, 0.18),
        )
        page.draw_line(fitz.Point(54, 88), fitz.Point(541, 88), color=(0.55, 0.61, 0.72), width=0.8)

        y = 122
        for level, title, target_page in chunk:
            indent = min(max(level - 1, 0), 2) * 18
            font_size = 12 if level == 1 else 10.5
            color = (0.08, 0.16, 0.33) if level == 1 else (0.20, 0.25, 0.34)
            page.insert_text(
                fitz.Point(54 + indent, y),
                str(title),
                fontsize=font_size,
                fontname="helv",
                color=color,
            )
            page.insert_text(
                fitz.Point(510, y),
                str(target_page + target_offset),
                fontsize=font_size,
                fontname="helv",
                color=color,
            )
            y += 24 if level == 1 else 20

    return contents_doc


def extract_pdf_index_entries(document: fitz.Document, fallback_title: str) -> List[List]:
    """Create useful automatic index entries when a PDF has no outline."""
    entries = []
    for page_index in range(len(document)):
        lines = [
            " ".join(line.split())
            for line in document.load_page(page_index).get_text().splitlines()
            if line.strip()
        ]
        heading = next(
            (line for line in lines if 3 <= len(line) <= 100 and line.lower() not in {"contents", "table of contents"}),
            None,
        )
        entries.append([1, heading or (fallback_title if page_index == 0 else f"{fallback_title} - Page {page_index + 1}"), page_index + 1])
    return entries


def merge_pdfs(
    items: List[Dict],
    title: str = "Study Material Collection",
    add_cover_page: bool = True,
    add_source_separator: bool = True,
    generate_toc: bool = True
) -> Tuple[Optional[str], int, float]:
    """
    Merges multiple PDFs, optionally adding cover/separator pages and TOC.
    Returns (filename, total_pages, size_mb)
    """
    try:
        merged_doc = fitz.open()
        output_dir = get_output_dir()
        
        # Inspect sources once so page targets remain correct after Contents is inserted.
        total_pages = 0
        valid_items = []
        source_tocs = {}
        for item in items:
            pdf_path = output_dir / item['filename']
            if pdf_path.exists():
                doc = fitz.open(pdf_path)
                total_pages += len(doc)
                if add_source_separator:
                    total_pages += 1
                source_toc = doc.get_toc() or extract_pdf_index_entries(
                    doc,
                    item.get('title') or Path(item['filename']).stem,
                )
                unique_source_toc = []
                for entry in source_toc:
                    if entry not in unique_source_toc:
                        unique_source_toc.append(entry)
                source_tocs[item['filename']] = unique_source_toc
                doc.close()
                valid_items.append(item)
                
        if not valid_items:
            logger.error("No valid PDFs to merge.")
            return None, 0, 0.0

        cover_pages = 1 if add_cover_page else 0
        content_entries = []
        for index, item in enumerate(valid_items):
            source_title = item.get('title') or f"Source {index + 1}"
            content_entries.append([1, source_title, 0])
            source_root_skipped = any(
                entry[1].strip() == source_title.strip() and entry[2] == 1
                for entry in source_tocs.get(item['filename'], [])
            )
            for entry in source_tocs.get(item['filename'], []):
                if entry[1].strip() == source_title.strip() and entry[2] == 1:
                    continue
                level = entry[0] if source_root_skipped else entry[0] + 1
                content_entries.append([level, entry[1], 0])
        toc_pages = max(1, (len(content_entries) + 27) // 28) if generate_toc else 0
        total_pages += cover_pages + toc_pages
        
        temp_files = []
        
        # 1. Cover Page
        if add_cover_page:
            cover_path = output_dir / f"temp_cover_{generate_unique_filename()}"
            temp_files.append(cover_path)
            create_cover_page(title, len(valid_items), total_pages, cover_path)
            cover_doc = fitz.open(cover_path)
            merged_doc.insert_pdf(cover_doc)
            cover_doc.close()
            
        # 2. Table of Contents (Placeholder if needed, or just bookmarks)
        toc = []
        current_page = len(merged_doc) + 1 # 1-based index for TOC
        
        # 3. Source Pages
        for idx, item in enumerate(valid_items):
            source_title = item.get('title') or f"Source {idx+1}"
            
            if add_source_separator:
                sep_path = output_dir / f"temp_sep_{idx}_{generate_unique_filename()}"
                temp_files.append(sep_path)
                create_separator_page(idx + 1, source_title, item['url'], sep_path)
                sep_doc = fitz.open(sep_path)
                merged_doc.insert_pdf(sep_doc)
                sep_doc.close()
            
            # Record TOC entry (level, title, page)
            toc.append([1, source_title, current_page])
            
            # Insert main PDF
            pdf_path = output_dir / item['filename']
            src_doc = fitz.open(pdf_path)
            
            # Try to preserve sub-bookmarks if possible
            src_toc = source_tocs.get(item['filename'], [])
            source_root_skipped = any(
                entry[1].strip() == source_title.strip() and entry[2] == 1
                for entry in src_toc
            )
            for entry in src_toc:
                if entry[1].strip() == source_title.strip() and entry[2] == 1:
                    continue
                # Shift level down and adjust page number
                entry[0] = entry[0] if source_root_skipped else entry[0] + 1
                entry[2] += current_page - 1
                if add_source_separator:
                     entry[2] += 1
                toc.append(entry)
                
            merged_doc.insert_pdf(src_doc)
            current_page += len(src_doc)
            if add_source_separator:
                 current_page += 1
            src_doc.close()

        if generate_toc:
            for index, entry in enumerate(toc):
                content_entries[index][2] = entry[2]
            contents_doc = create_contents_pdf(content_entries, toc_pages)
            merged_doc.insert_pdf(contents_doc, start_at=0)
            contents_doc.close()
            for contents_page_index, chunk_start in enumerate(range(0, len(content_entries), 28)):
                page = merged_doc.load_page(contents_page_index)
                y = 122
                for level, _title, target_page in content_entries[chunk_start:chunk_start + 28]:
                    indent = min(max(level - 1, 0), 2) * 18
                    page.insert_link({
                        "kind": fitz.LINK_GOTO,
                        "from": fitz.Rect(48 + indent, y - 15, 535, y + 7),
                        "page": target_page - 1 + toc_pages,
                    })
                    y += 24 if level == 1 else 20
            toc = [[level, title, page + toc_pages] for level, title, page in toc]

        # Apply TOC / Bookmarks
        if generate_toc:
            merged_doc.set_toc(toc)

        # Set Metadata
        merged_doc.set_metadata({
            "title": title,
            "author": "Page2PDF",
            "subject": "Web Study Material Collection",
            "keywords": "study, educational, webpage, PDF",
            "creator": "Page2PDF"
        })

        # Save merged PDF
        final_filename = f"collection_{generate_unique_filename()}"
        final_path = output_dir / final_filename
        
        # Save with garbage collection/deflate
        merged_doc.save(final_path, garbage=3, deflate=True)
        final_page_count = len(merged_doc)
        merged_doc.close()
        
        # Cleanup temp files
        for temp_file in temp_files:
            try:
                if temp_file.exists():
                    temp_file.unlink()
            except Exception as e:
                logger.warning(f"Failed to delete temp file {temp_file}: {e}")

        size_mb = final_path.stat().st_size / (1024 * 1024)
        logger.info(f"Merged PDF created: {final_filename} ({size_mb:.2f} MB, {final_page_count} pages)")
        
        return final_filename, final_page_count, size_mb
        
    except Exception as e:
        logger.error(f"Error merging PDFs: {e}", exc_info=True)
        return None, 0, 0.0


def edit_pdf_pages(input_filename: str, keep_pages: List[int], rotations: Optional[Dict[int, int]] = None) -> Tuple[Optional[str], int, float]:
    """
    Creates a new PDF containing only the specified pages (0-indexed) in the specified order.
    Applies rotations if provided.
    """
    try:
        output_dir = get_output_dir()
        input_path = output_dir / input_filename
        
        if not input_path.exists():
            logger.error(f"Input PDF not found for editing: {input_path}")
            return None, 0, 0.0
            
        source_doc = fitz.open(input_path)
        output_doc = fitz.open()
        
        # Ensure pages are within valid range (but DO NOT sort them, to preserve user ordering)
        valid_pages = [p for p in keep_pages if 0 <= p < len(source_doc)]
        
        if not valid_pages:
             logger.error("No valid pages selected to keep.")
             source_doc.close()
             output_doc.close()
             return None, 0, 0.0
             
        for new_idx, source_idx in enumerate(valid_pages):
            output_doc.insert_pdf(source_doc, from_page=source_idx, to_page=source_idx)
            if rotations and str(source_idx) in rotations:
                page = output_doc.load_page(new_idx)
                page.set_rotation(rotations[str(source_idx)])
            elif rotations and source_idx in rotations:
                page = output_doc.load_page(new_idx)
                page.set_rotation(rotations[source_idx])
            
        # Copy metadata
        output_doc.set_metadata(source_doc.metadata)
        
        edited_filename = f"edited_{generate_unique_filename()}.pdf"
        edited_path = output_dir / edited_filename
        
        output_doc.save(edited_path, garbage=3, deflate=True)
        
        final_page_count = len(output_doc)
        source_doc.close()
        output_doc.close()
        
        size_mb = edited_path.stat().st_size / (1024 * 1024)
        return edited_filename, final_page_count, size_mb
        
    except Exception as e:
        logger.error(f"Error editing PDF pages: {e}", exc_info=True)
        return None, 0, 0.0


def get_pdf_thumbnail(filename: str, page_index: int, zoom: float = 0.5) -> Optional[bytes]:
    """
    Generates a PNG thumbnail for a specific PDF page.
    page_index is 0-based.
    zoom determines the resolution. 0.5 is low res, 2.0 is high res.
    """
    try:
        output_dir = get_output_dir()
        pdf_path = output_dir / filename
        
        if not pdf_path.exists():
            return None
            
        doc = fitz.open(pdf_path)
        if page_index < 0 or page_index >= len(doc):
            doc.close()
            return None
            
        page = doc.load_page(page_index)
        mat = fitz.Matrix(zoom, zoom)
        pix = page.get_pixmap(matrix=mat, alpha=False)
        img_bytes = pix.tobytes("png")
        
        doc.close()
        return img_bytes
        
    except Exception as e:
        logger.error(f"Error generating thumbnail: {e}", exc_info=True)
        return None

def insert_file_into_pdf(base_filename: str, insert_path: Path, position: str, page_index: int = 0) -> Tuple[Optional[str], int, float]:
    """
    Inserts a PDF or image into the base PDF.
    position: 'start', 'end', or 'after'
    page_index: 0-indexed page after which to insert (if position=='after')
    """
    try:
        output_dir = get_output_dir()
        base_path = output_dir / base_filename
        
        if not base_path.exists():
            logger.error("Base PDF not found.")
            return None, 0, 0.0
            
        base_doc = fitz.open(base_path)
        
        # Handle images
        if insert_path.suffix.lower() in ['.png', '.jpg', '.jpeg', '.webp']:
            pdfbytes = _standardize_image_pdf_bytes(insert_path)
            if not pdfbytes:
                base_doc.close()
                return None, 0, 0.0
            insert_doc = fitz.open("pdf", pdfbytes)
        else:
            insert_doc = fitz.open(insert_path)
            
        # Determine insertion index
        if position == 'start':
            insert_at = 0
        elif position == 'end':
            insert_at = len(base_doc)
        else:
            # 'after'
            insert_at = min(page_index + 1, len(base_doc))
            
        base_doc.insert_pdf(insert_doc, start_at=insert_at)
        
        new_filename = f"edited_{generate_unique_filename()}.pdf"
        new_path = output_dir / new_filename
        
        base_doc.save(new_path, garbage=3, deflate=True)
        final_page_count = len(base_doc)
        
        base_doc.close()
        insert_doc.close()
        
        size_mb = new_path.stat().st_size / (1024 * 1024)
        return new_filename, final_page_count, size_mb
        
    except Exception as e:
        logger.error(f"Error inserting file: {e}", exc_info=True)
        return None, 0, 0.0


def _standardize_image_pdf_bytes(image_path: Path) -> Optional[bytes]:
    """Place an image proportionally on a standard A4 page."""
    try:
        pixmap = fitz.Pixmap(str(image_path))
        page_width, page_height = 595.0, 842.0
        margin = 36.0
        available_width = page_width - (margin * 2)
        available_height = page_height - (margin * 2)
        scale = min(available_width / pixmap.width, available_height / pixmap.height)
        image_width = pixmap.width * scale
        image_height = pixmap.height * scale
        left = (page_width - image_width) / 2
        top = (page_height - image_height) / 2

        pdf_doc = fitz.open()
        page = pdf_doc.new_page(width=page_width, height=page_height)
        page.insert_image(
            fitz.Rect(left, top, left + image_width, top + image_height),
            pixmap=pixmap,
            keep_proportion=True,
        )
        pdf_bytes = pdf_doc.tobytes(garbage=3, deflate=True)
        pdf_doc.close()
        return pdf_bytes
    except Exception as e:
        logger.error(f"Error standardizing image: {e}", exc_info=True)
        return None


def convert_image_to_pdf(image_path: Path, output_path: Path) -> bool:
    """Convert an image into a standard A4 PDF page."""
    try:
        pdf_bytes = _standardize_image_pdf_bytes(image_path)
        if not pdf_bytes:
            return False
        pdf_doc = fitz.open("pdf", pdf_bytes)
        pdf_doc.save(output_path)
        pdf_doc.close()
        return True
    except Exception as e:
        logger.error(f"Error converting image to PDF: {e}", exc_info=True)
        return False

